### ISSUE TITLE
Preset not working

### ISSUE THREAD

**Issue by evazzoler** [hobbyquaker/node-red-contrib-wled#2]
Hi,
passing a number as string for changing the preset is currently not working.
Am I doing something wrong or is the docu wrong?

**Comment by giannisj5** [comment]
i have the same issue, presets are not working nor the effects

msg : error
"TypeError: Cannot read properties of undefined (reading 'includes')"

**Comment by parish99** [comment]
I am getting the same error, but things still function and the light is set to the preset that is sent.

`TypeError: Cannot read properties of undefined (reading 'includes')
    at WledNode._inputCallback (/config/node_modules/node-red-contrib-wled/nodes/wled.js:41:43)
    at /opt/node_modules/@node-red/runtime/lib/nodes/Node.js:214:26
    at Object.trigger (/opt/node_modules/@node-red/util/lib/hooks.js:166:13)
    at WledNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:206:11)
    at WledNode.Node.emit (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:190:25)
    at WledNode.Node.receive (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:499:10)
    at deliverMessageToDestination (/opt/node_modules/@node-red/runtime/lib/flows/Flow.js:800:40)
    at Immediate._onImmediate (/opt/node_modules/@node-red/runtime/lib/flows/Flow.js:816:21)
    at processImmediate (node:internal/timers:476:21)`
